services:
  typesense:
    image: typesense/typesense:26.0
    container_name: typesense
    env_file:
      - .env
    ports:
      - "8108:8108"
    volumes:
      - typesense_data:/data
    environment:
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY}
      TYPESENSE_DATA_DIR: /data
    restart: on-failure
  
  wppconnect:
    image: registry.v75inc.dev/wppconnect/wppconnect_prod:latest
    container_name: wppconnect
    env_file:
      - .env
    ports:
      - "21465:21465" # wppconnect API
    volumes:
      - wppconnect_tokens:/usr/src/wpp-server/tokens
      - wppconnect_user_data:/usr/src/wpp-server/userDataDir
    restart: on-failure

volumes:
  typesense_data:
  wppconnect_tokens:
  wppconnect_user_data: